name: export
on: [ push, pull_request ]

jobs:
  export:
    #    runs-on: ${{ matrix.os }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - name: Show Environment Variables
        run: export
